#!/bin/bash

if [ -z "$HOME" ]; then
  echo "Where is your \$HOME?";
  exit 1;
fi

# Set up consts
GITCLONE="git clone --depth=1"
DOTFILES=$HOME/.dotfiles
DOTFZF=$HOME/.fzf
DOTLOCAL=$HOME/.local/share/dotfiles
ZSHRC=$HOME/.zshrc
VIMRC=$HOME/.vimrc
VIMDIR=$HOME/.vim
GCONF=$HOME/.gitconfig

declare -a to_backup=($DOTFILES $DOTFZF $DOTLOCAL $ZSHRC
                      $VIMRC $VIMDIR $GCONF)
declare -a dirs_to_create=($DOTFILES $DOTFZF $VIMDIR)
declare -a files_to_link=("$DOTFILES/zshrc:$ZSHRC"
                          "$DOTFILES/vimrc:$VIMRC"
                          "$DOTFILES/gitconfig:$GCONF")

cd $HOME

for item in "${to_backup[@]}"; do
  if [ -d $item ] || [ -f $item ] || [ -L $item ]; then
    echo "$item exists already, moving to $item.old";
    if [ -d "$item.old" ] || [ -f "$item.old" ] || [ -L "$item.old" ]; then
      echo "$item.old also exists already, removing it";
      rm -rf "$item.old";
    fi
    mv $item "$item.old";
  fi
done

for i in "${dirs_to_create[@]}"; do
  echo "Creating directory: $i";
  mkdir $i;
done

for i in "${files_to_link[@]}"; do
  KEY=${i%%:*}
  VAL=${i#*:}
  echo "Creating symlink: $VAL -> $KEY";
  ln -s $KEY $VAL;
done

cd $DOTFILES

git init
git remote add origin git@github.com:zachschultz/dotfiles.git
git pull origin master
git submodule update --init --recursive

echo
echo "Done!"
