#!/bin/bash

if [ -z "$HOME" ]; then
  echo "Where is your \$HOME?";
  exit 1;
fi

# Set up consts
GITCLONE="git clone --depth=1"
DOTFILES=$HOME/.dotfiles
DOTFZF=$HOME/.fzf
DOTLOCAL=$HOME/.local/share/dotfiles
ZSHRC=$HOME/.zshrc
VIMRC=$HOME/.vimrc
VIMDIR=$HOME/.vim
GCONF=$HOME/.gitconfig

declare -a to_backup=($DOTFILES $DOTFZF $DOTLOCAL $ZSHRC
                      $VIMRC $VIMDIR $GCONF)
declare -a dirs_to_create=($DOTFILES $DOTFZF $VIMDIR)
declare -a files_to_link=("$DOTFILES/zshrc:$ZSHRC"
                          "$DOTFILES/vimrc:$VIMRC"
                          "$DOTFILES/gitconfig:$GCONF")

cd $HOME

echo "I am going to search for the following files and back them up"
printf '%s\n' "${to_backup[@]}"
echo
read -p "Continue? [Y\\n]" -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
  [[ "$0" = "$BASH_SOURCE" ]] && exit 1 || return 1
fi

##############################################
# Backup and remove existing files
##############################################
for item in "${to_backup[@]}"; do
  if [ -d $item ] || [ -f $item ] || [ -L $item ]; then
    echo "$item exists already, moving to $item.old";
    if [ -d "$item.old" ] || [ -f "$item.old" ] || [ -L "$item.old" ]; then
      echo "$item.old also exists already, removing it";
      rm -rf "$item.old";
    fi
    mv $item "$item.old";
  fi
done

##############################################
# Create directories
##############################################
for i in "${dirs_to_create[@]}"; do
  echo "Creating directory: $i";
  mkdir $i;
done

##############################################
# Symlink dotfiles to home dir
##############################################
for i in "${files_to_link[@]}"; do
  KEY=${i%%:*}
  VAL=${i#*:}
  echo "Creating symlink: $VAL -> $KEY";
  ln -s $KEY $VAL;
done

cd $DOTFILES

##############################################
# Clone the dotfiles repo 
##############################################
git init
git remote add origin git@github.com:zachschultz/dotfiles.git
git pull origin master
git submodule update --init --recursive

# Clone some zsh-users plugins
$GITCLONE https://github.com/zsh-users/zsh-completions.git $DOTLOCAL/zsh-completions
$GITCLONE https://github.com/zsh-users/zsh-history-substring-search.git $DOTLOCAL/zsh-history-substring-search
$GITCLONE https://github.com/zsh-users/zsh-syntax-highlighting.git $DOTLOCAL/zsh-syntax-highlighting
echo
echo "Done!"
